language: python
python:
    - "3.4"
    #- "3.6"

install:
    - pip install -r requirements.txt
    - ln -s test/data/pav_config_dir/pavilion.yaml.travis-ci test/data/pav_config_dir/pavilion.yaml
    - ls -lh test/data/pav_config_dir

script: 
    - ./test/run_tests
    
