language: python
python:
    - "3.4"
    #- "3.6"

install:
    - pip install -r requirements.txt
    - ln -s test/data/pav_config_dir/pavilion.yaml.travis-ci test/data/pav_config_dir/pavilion.yaml
    - ls -lh ./test/data/pav_config_dir
    - find ./test/data

script: 
    - cat /home/travis/build/hpc/pavilion2/test/data/pav_config_dir/pavilion.yaml
    - ./test/run_tests
    
